#!/bin/sh
set -e

echo "debian/rules override_dh_auto_configure "
debian/rules override_dh_auto_configure

# Supress gcc warnings (autopkg treats them as failures)
make tls getgroups getfsdev trimslash t_unsafe wildtest testrun 2>/dev/null

# Run tests
rsync_bin="/usr/bin/rsync" ./runtests.sh
